import type { Page } from "@/lib/content";

export const dashboardUrl = "https://ready-margin-sbos-review.gsm-consulta-8479.chatgpt.site/";
export const productDisclosure = "Real screenshots from the Ready Margin demo. Sample data; providers and payroll engines are not connected.";

export const productShots = {
  overview: { src: "/product/overview.png", title: "Operations overview", alt: "Ready Margin operations overview showing cash, attendance exceptions, held tips and the weekly close." },
  schedule: { src: "/product/schedule.png", title: "Schedule", alt: "Ready Margin weekly schedule with employee shifts, scheduled hours and projected base wages." },
  attendance: { src: "/product/attendance.png", title: "Attendance", alt: "Ready Margin attendance table showing missing clock-outs, late arrivals and the payroll handoff." },
  attendanceDetail: { src: "/product/attendance-detail.png", title: "Attendance source record", alt: "Ready Margin punch details drawer retaining Avery Demo’s original clock-in and missing clock-out." },
  tips: { src: "/product/tips.png", title: "Tickets & tips", alt: "Ready Margin tickets and tips view with a held check, unmatched server and recorded tip amounts." },
  payroll: { src: "/product/payroll.png", title: "Payroll runs", alt: "Ready Margin payroll runs showing an open operating week, time records to review and held tips." },
  readiness: { src: "/product/readiness.png", title: "Week readiness", alt: "Ready Margin week readiness listing outstanding attendance, tip and adjustment questions with their next owners." },
  weeklyClose: { src: "/product/weekly-close.png", title: "Weekly close", alt: "Ready Margin weekly close with attendance, tickets, tip rules, pool shares, adjustments and final-review steps." },
  entrySheet: { src: "/product/entry-sheet.png", title: "Closed payroll entry sheet", alt: "Ready Margin read-only payroll entry sheet showing recorded hours, rates, tips and gross amounts from a closed sample week." },
  bills: { src: "/product/bills.png", title: "Recurring bills", alt: "Ready Margin recurring bills table showing sample rent and linen obligations, due dates and review status." },
  reconciliation: { src: "/product/reconciliation.png", title: "Reconciliation", alt: "Ready Margin reconciliation cards separating matched, possible and unmatched transactions with source evidence." },
  cash: { src: "/product/cash.png", title: "Cash position", alt: "Ready Margin cash view showing an observed account balance, upcoming bills and the limits of the available projection data." },
} as const;
export type ProductShotId = keyof typeof productShots;

export const productWorkflows = [
  { id: "schedule", label: "Schedule", shot: "schedule", title: "Plan the week before it starts.", body: "See who is scheduled, where they’re working and the base wages attached to the plan. We help connect that plan to the hours you’ll review after service.", points: ["Shifts by person and day", "Scheduled hours and base wage context", "A clear starting point for attendance review"], href: "/restaurant-labor-cost-management", link: "Explore labor support" },
  { id: "attendance", label: "Attendance", shot: "attendance", title: "Confirm the hours before payroll.", body: "Review missing punches and late arrivals against the schedule. Our team collects manager confirmation and documents corrections before payroll preparation.", points: ["Original and current time records together", "The reason behind a correction", "Manager confirmation before the handoff"], href: "/restaurant-payroll-services", link: "Explore payroll support" },
  { id: "tips", label: "Tips", shot: "tips", title: "Keep held tips in view.", body: "An unmatched name or missing tip rule should remain an open question. We help trace the check, identify what’s missing and get the decision to the responsible person.", points: ["Check amounts and recorded tips", "Unmatched names and held money", "A person responsible for each open question"], href: "/restaurant-payroll-services", link: "Explore payroll and tips" },
  { id: "payroll", label: "Payroll", shot: "readiness", title: "See what payroll still needs.", body: "Attendance, tip evidence and adjustments each have their own next owner. We help keep that review moving so the payroll handoff carries the records and decisions it needs.", points: ["Outstanding work by source", "A named person for the next action", "The questions to resolve before approval"], href: "/restaurant-payroll-services", link: "Explore payroll support" },
  { id: "bills", label: "Bills", shot: "bills", title: "Give every bill a next check.", body: "See the payee, amount, due date and review state together. We help maintain the agreed records and follow up on open questions before the restaurant decides on payment.", points: ["Recurring obligations and due dates", "Items that still need review", "Payment approval stays with your restaurant"], href: "/restaurant-accounts-payable-services", link: "Explore payables support" },
  { id: "reconciliation", label: "Books", shot: "reconciliation", title: "Follow a match back to its source.", body: "A possible match is a question to review. We check the bank line and books counterpart, explain the evidence and keep unmatched activity visible until it has an answer.", points: ["Matched, possible and unmatched records", "Bank and books references together", "Human confirmation of the evidence"], href: "/restaurant-accounting-services", link: "Explore accounting support" },
  { id: "cash", label: "Cash", shot: "cash", title: "Put obligations beside the balance.", body: "A bank balance tells you what was observed. We bring the bills, timing and missing information into the discussion, so the next financial decision starts with the records.", points: ["Account balances with observation times", "Recorded upcoming obligations", "Clear limits when forecast inputs are missing"], href: "/restaurant-cfo-services", link: "Explore CFO guidance" },
] as const;

export function serviceProductFor(page: Pick<Page, "path" | "kind">) {
  if (!["service", "service-hub", "capability", "capability-index", "process", "rhythm", "platform", "workstreams", "owner-view", "solution", "solution-hub"].includes(page.kind)) return null;
  const path = page.path;
  if (["process", "rhythm", "workstreams"].includes(page.kind)) return { shot: "weeklyClose" as const, title: "Give the weekly review a clear sequence.", body: "The demo keeps attendance, tickets, tip rules, pool shares and adjustments in separate review steps. We help gather the agreed records, resolve open questions and document the handoff before the restaurant gives its defined approvals.", points: ["Review one source at a time", "Keep missing evidence visible", "Carry decisions through to the final review"] };
  if (/tip/.test(path)) return { shot: "tips" as const, title: "Keep the check, the tip and the open question together.", body: "This demo keeps held tips separate from routed checks. Our payroll and tips support helps trace the source records, document the missing evidence and get the next action to the right person.", points: ["Recorded checks and tip amounts", "Held money remains visible", "Your restaurant supplies and approves the applicable rules"] };
  if (/attendance/.test(path)) return { shot: "attendanceDetail" as const, title: "Resolve the exception against the original record.", body: "Original punches, current times and the correction reason stay together. We help follow up with the manager and prepare the agreed records for the payroll handoff.", points: ["Keep the original source", "Document the correction", "Confirm the hours before handoff"] };
  if (/payroll/.test(path)) return { shot: "readiness" as const, title: "A payroll handoff with a clear next owner.", body: "The readiness view separates attendance, held checks, tip rules and adjustments. We help chase the outstanding answers and keep the review trail together; the restaurant retains its defined approvals.", points: ["Know what remains open", "See who acts next", "Carry the source evidence into the handoff"] };
  if (/labor|scheduling|schedule/.test(path)) return { shot: "schedule" as const, title: "Connect the planned week to the hours you review.", body: "The schedule shows shifts, departments, hours and base wage context. We help compare the operating plan with the attendance and labor records that inform your financial review.", points: ["See shifts by person and day", "Review scheduled hours", "Use base wages as planning context, before taxes, tips and premiums"] };
  if (/payable|vendor|bill/.test(path)) return { shot: "bills" as const, title: "See the obligation and the next check together.", body: "The recurring-bills view keeps amounts, due dates and review states in one place. We help maintain the agreed payables records and follow up on questions before the restaurant approves payment.", points: ["Record payee, amount and timing", "Keep unresolved items visible", "A handled bill is not evidence of a payment"] };
  if (/accounting|bookkeeping|books|reconcil/.test(path)) return { shot: "reconciliation" as const, title: "A clearer route from transaction to explanation.", body: "The demo separates confirmed matches, possible matches and unmatched activity. Our accounting and bookkeeping work checks the evidence, follows up on gaps and supports a close you can review.", points: ["Bank and books references together", "Review the reason for a possible match", "Keep unexplained activity open"] };
  if (/tax|compliance|report/.test(path)) return { shot: "entrySheet" as const, title: "Keep the closed record available for the next handoff.", body: "The demo’s entry sheet preserves recorded hours, rates, tips and gross amounts for a closed payroll week. We help organize the agreed finance records for reporting and professional review. This shot shows a payroll record, not a tax filing or net-pay calculation.", points: ["A read-only record of the closed week", "Recorded inputs and their source", "A clear handoff to the relevant professional"] };
  if (/cash|cfo|turnaround|profit/.test(path)) return { shot: "cash" as const, title: "Start the cash conversation with what is known.", body: "Observed balances and recorded bills belong in the same review. We help explain the timing, identify missing information and turn the records into questions and priorities your restaurant can decide on.", points: ["Observed balances with timestamps", "Obligations that are already recorded", "No forecast presented when its inputs are missing"] };
  if (/food|inventory|cost/.test(path)) return { shot: "bills" as const, title: "Bring the cost question back to the records.", body: "Our cost-control support starts with the agreed supplier, purchasing, stock and labor records. This demo shot illustrates bill amounts, timing and follow-up; recipe costing and inventory tracking are outside the view shown here.", points: ["Check the source of a cost change", "Agree who confirms the answer", "Use confirmed records in the next operating review"] };
  return { shot: "overview" as const, title: "One place to see what needs an answer.", body: "The overview brings attendance exceptions, held tips, cash context and the weekly review together. Our team handles the agreed finance work and keeps questions moving to the person who can resolve them.", points: ["Urgent work stays visible", "The weekly review has clear steps", "Responsibilities are agreed with your restaurant"] };
}
