import type { Page } from "@/lib/content";

export const dashboardUrl = "https://ready-margin-sbos-review.gsm-consulta-8479.chatgpt.site/";
export const productDisclosure = "The public demo uses sample records. Banking and payroll providers are not connected.";

export const productShots = {
  overview: { src: "/product/overview.png", title: "Operations overview", alt: "Ready Margin operations overview showing cash, attendance exceptions, held tips and the weekly close." },
  schedule: { src: "/product/schedule.png", title: "Schedule", alt: "Ready Margin weekly schedule with employee shifts, scheduled hours and projected base wages." },
  attendance: { src: "/product/attendance.png", title: "Attendance", alt: "Ready Margin attendance table showing missing clock-outs, late arrivals and the payroll handoff." },
  attendanceDetail: { src: "/product/attendance-detail.png", title: "Attendance source record", alt: "Ready Margin punch details drawer retaining Avery Demo’s original clock-in and missing clock-out." },
  tips: { src: "/product/tips.png", title: "Tickets & tips", alt: "Ready Margin tickets and tips view with a held check, unmatched server and recorded tip amounts." },
  payroll: { src: "/product/payroll.png", title: "Payroll runs", alt: "Ready Margin payroll runs showing an open operating week, time records to review and held tips." },
  readiness: { src: "/product/readiness.png", title: "Week readiness", alt: "Ready Margin week readiness listing outstanding attendance, tip and adjustment questions with their next owners." },
  weeklyClose: { src: "/product/weekly-close.png", title: "Weekly close", alt: "Ready Margin weekly close with attendance, tickets, tip rules, pool shares, adjustments and final-review steps." },
  entrySheet: { src: "/product/entry-sheet.png", title: "Closed payroll entry sheet", alt: "Ready Margin read-only payroll entry sheet showing recorded hours, rates, tips and gross amounts from a closed sample week." },
  bills: { src: "/product/bills.png", title: "Recurring bills", alt: "Ready Margin recurring bills table showing sample rent and linen obligations, due dates and review status." },
  reconciliation: { src: "/product/reconciliation.png", title: "Reconciliation", alt: "Ready Margin reconciliation cards separating matched, possible and unmatched transactions with source evidence." },
  cash: { src: "/product/cash.png", title: "Cash position", alt: "Ready Margin cash view showing an observed account balance, upcoming bills and the limits of the available projection data." },
} as const;
export type ProductShotId = keyof typeof productShots;

export const productWorkflows = [
  { id: "schedule", label: "Schedule", shot: "schedule", title: "Review the scheduled shifts and base wages.", body: "This view lists planned shifts, hours and base wages. Compare it with attendance after service; a schedule estimate does not include every employment cost.", points: ["Shifts by person and day", "Scheduled hours and base wage context", "A clear starting point for attendance review"], href: "/restaurant-labor-cost-management", link: "Explore labor support" },
  { id: "attendance", label: "Attendance", shot: "attendance", title: "Check attendance exceptions with the manager.", body: "The attendance review identifies missing punches and other exceptions. We obtain manager confirmation and retain the correction reason before preparing the payroll input.", points: ["Original and current time records together", "The reason behind a correction", "Manager confirmation before the handoff"], href: "/restaurant-payroll-services", link: "Explore payroll support" },
  { id: "tips", label: "Tips", shot: "tips", title: "Trace unmatched checks and held tip amounts.", body: "The tip view separates recorded amounts from questions awaiting an employee assignment or confirmed rule. The responsible person supplies that evidence before the input can be approved.", points: ["Check amounts and recorded tips", "Unmatched names and held money", "A person responsible for each open question"], href: "/restaurant-payroll-services", link: "Explore payroll and tips" },
  { id: "payroll", label: "Payroll", shot: "readiness", title: "Review the inputs still needed for payroll.", body: "The readiness list groups unresolved attendance, tip and adjustment items. It identifies the contact supplying each answer before the restaurant reviews the prepared payroll inputs.", points: ["Outstanding work by source", "A named person for the next action", "The questions to resolve before approval"], href: "/restaurant-payroll-services", link: "Explore payroll support" },
  { id: "bills", label: "Bills", shot: "bills", title: "Check recurring bills and their due dates.", body: "The bill list records amounts, dates and review status. We maintain the agreed records and follow up on missing information; the authorized restaurant contact decides on payment.", points: ["Recurring obligations and due dates", "Items that still need review", "Payment approval stays with your restaurant"], href: "/restaurant-accounts-payable-services", link: "Explore payables support" },
  { id: "reconciliation", label: "Books", shot: "reconciliation", title: "Compare bank activity with the accounting record.", body: "Confirmed matches, possible matches and unmatched entries are separate. We check the supporting statements and accounting references before confirming the reconciliation.", points: ["Matched, possible and unmatched records", "Bank and books references together", "Each match checked against its source"], href: "/restaurant-accounting-services", link: "Explore accounting support" },
  { id: "cash", label: "Cash", shot: "cash", title: "Compare dated balances with recorded obligations.", body: "The cash view shows an observed balance and the obligations recorded in the demo. Missing projection inputs are identified rather than used to present an unsupported forecast.", points: ["Account balances with observation times", "Recorded upcoming obligations", "Clear limits when forecast inputs are missing"], href: "/restaurant-cfo-services", link: "Explore CFO guidance" },
] as const;

export function serviceProductFor(page: Pick<Page, "path" | "kind">) {
  if (!["service", "service-hub", "capability", "capability-index", "process", "rhythm", "platform", "workstreams", "owner-view", "solution", "solution-hub"].includes(page.kind)) return null;
  const path = page.path;
  // The captured demo has no stock-count or recipe-costing view.
  if (/food|inventory/.test(path)) return null;
  if (["process", "rhythm", "workstreams"].includes(page.kind)) return { shot: "weeklyClose" as const, title: "Review the weekly payroll inputs in stages.", body: "The weekly review separates attendance, tickets, tip rules, pool shares and adjustments. Each step needs its supporting inputs before the prepared record reaches the restaurant’s approver.", points: ["Review one source at a time", "Keep missing evidence visible", "Carry decisions through to the final review"] };
  if (/tip/.test(path)) return { shot: "tips" as const, title: "Check the tip amount and employee assignment.", body: "The demo separates held amounts from routed checks. Tip preparation traces the source and asks the responsible contact for a missing employee assignment or approved rule.", points: ["Recorded checks and tip amounts", "Held money remains visible", "Your restaurant supplies and approves the applicable rules"] };
  if (/attendance/.test(path)) return { shot: "attendanceDetail" as const, title: "Review the original punch before a correction.", body: "The original punch remains beside the current entry and correction reason. The manager confirms worked hours before the approved correction enters payroll preparation.", points: ["Keep the original source", "Document the correction", "Confirm the hours before handoff"] };
  if (/payroll/.test(path)) return { shot: "readiness" as const, title: "Identify the payroll inputs awaiting confirmation.", body: "The readiness view lists missing attendance, check, rule and adjustment evidence with the responsible contact. Our preparation service follows up on those inputs before the restaurant’s authorization.", points: ["Know what remains open", "See who acts next", "Carry the source evidence into the handoff"] };
  if (/labor|scheduling|schedule/.test(path)) return { shot: "schedule" as const, title: "Compare planned coverage with recorded time.", body: "Scheduled hours and base wages describe the operating plan. Attendance and other employment costs are needed to review actual labor cost for the same period.", points: ["See shifts by person and day", "Review scheduled hours", "Use base wages as planning context, before taxes, tips and premiums"] };
  if (/payable|vendor|bill/.test(path)) return { shot: "bills" as const, title: "Review bill amounts, dates and approval status.", body: "The recurring-bill list identifies the obligation and review status. Payables support maintains those records and obtains missing information for the restaurant’s payment decision.", points: ["Record payee, amount and timing", "Keep unresolved items visible", "A handled bill is not evidence of a payment"] };
  if (/accounting|bookkeeping|books|reconcil/.test(path)) return { shot: "reconciliation" as const, title: "Trace unmatched accounting entries to their sources.", body: "The reconciliation view separates confirmed, possible and unmatched entries. Our accounting work examines the source statements and follows up on unexplained amounts before the close.", points: ["Bank and books references together", "Review the reason for a possible match", "Keep unexplained activity open"] };
  if (/tax|compliance|report/.test(path)) return { shot: "entrySheet" as const, title: "Use the closed payroll record for the reporting handoff.", body: "The entry sheet shows recorded hours, rates, tips and gross amounts from a closed sample week. It illustrates a supporting record for reporting and professional review; it does not demonstrate tax filing or net-pay processing.", points: ["A read-only record of the closed week", "Recorded inputs and their source", "A clear handoff to the relevant professional"] };
  if (/cash|cfo|turnaround|profit/.test(path)) return { shot: "cash" as const, title: "Review the recorded cash position and payment dates.", body: "The view dates the observed balance and lists recorded bills. A financial review checks settlement timing and other commitments before management decides on payments or spending.", points: ["Observed balances with timestamps", "Obligations that are already recorded", "No forecast presented when its inputs are missing"] };
  return { shot: "overview" as const, title: "Review outstanding finance tasks in the overview.", body: "The overview shows sample attendance exceptions, held tips, balances and weekly preparation. Use it in the demo to discuss which records we would check and which contacts supply missing information.", points: ["Urgent work stays visible", "The weekly review has clear steps", "Responsibilities are agreed with your restaurant"] };
}
